### PR TITLE
Adding x64 artifact to Actions build

### PR DESCRIPTION
**Pull request by DarkWanderer**
- added 'install' step to pipeline
- added x64 artifact in `main` branch builds with 7 days retention
- switched to explicit invocation of cmake instead of "prefab" action use
  - allows to utilize "install" action, better customizability
  - lost "problem matchers" - compilation warnings will not be highlighted in CI (will still be logged!)
- switched to `main` from `master`

### CODE REVIEW

**Comment by DarkWanderer** [comment]
This will close #35

**Comment by DarkWanderer** [comment]
Note: artifact will not be visible in this PR, it would only be created on `main` branch

**Comment by mschweiger** [comment]
Unfortunately this update to the build.yml file seems to make the x64 build fail.
```
Error: "Build failed with error code: '1'."
    at Function.<anonymous> (D:\a\_actions\lukka\run-cmake\v3\dist\index.js:4117:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-cmake\v3\dist\index.js:3870:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: run-cmake action execution failed: 'Error: "Build failed with error code: '1'."'
```

**Comment by mschweiger** [comment]
Sorry false alarm. The build fail had nothing to do with the updated build.yml, but with the fact that I had unmerged pull requests to master. Solved now.

**Pull request merged**
