### PR TITLE
122 xrsound ci build

### PR DESCRIPTION
**Pull request by mschweiger**
Include XRSound build in CI build runs
- Download irrKlang package
- Cache package on CI server

### CODE REVIEW

**Comment by dbeachy1** [comment]
Nice work on this @mschweiger ! 👍

**Comment by mschweiger** [comment]
Thanks! Unfortunately it doesn't seem to work. XRSound is still not included in the build. I am investigating, but if anybody has an idea what the problem is, please let me know.

**Comment by mschweiger** [comment]
Everything seems to work now. I checked that
- The CI build triggers a failure if XRSound fails to build.
- The cache is successfully hit, avoiding repeated downloads of the irrKlang libraries.

The cache remains valid for a limited time (7 days). If no cache hit occurs during this period, the cache is deleted, next time a new download is performed. So in the worst case, there would be a download once a week, but in practice much less frequently. That shouldn't put any undue load on the irrKlang download server.
@dbeachy1 : If you are happy, I'll merge the branch.

**Comment by dbeachy1** [comment]
Great work, @mschweiger ! Looks good to me. 👍

**Review by dbeachy1 — APPROVED** [review]

**Pull request merged**
