### PR TITLE
246 user defined thruster groups

### LINKED ISSUE #246: Vessel class: thruster-group related functions don't fully support user-defined groups
Some thruster group methods, e.g. Vessel::GetThrusterGroupLevel, crash if called for a user-defined thruster group (ID >= THGROUP_USER).

### PR DESCRIPTION
**Pull request by mschweiger**
- User-defined thruster groups (THGROUP_USER+x with x >= 0) should now be fully supported by Vessel class methods and thruster-group related API functions.
- Some cleanup of code in Vessel class; converted thruster and thruster-group related lists to std::vector and std::array
- GetThrusterGroupLevel called with THGROUP_USER should no longer crash (see #235)

Closes #246

### CODE REVIEW

**Comment by mschweiger** [comment]
@spacex15 : It would be helpful if you can check if this pull request solves the problem identified in #235 (GetThrusterGroupLevel crashes with THGROUP_USER).

**Comment by spacex15** [comment]
@mschweiger I can confirm that calling GetThrusterGroupLevel(THGROUP_USER) no longer crashes and returns the thruster level for the first user group 
but I do not understand how to call GetThrusterGroupLevel for other id groups 
calling GetThrusterGroupLevel(THGROUP_USER+ groupindex )? (does not compile)
add another argument for the user group index ?

**Comment by mschweiger** [comment]
@spacex15 : you are correct, since the THGROUP_USER member of the THGROUP_TYPE enum was the upper bound of the enum, no valid addition was possible. I have now added an additional member to the enum to provide an extended upper bound. This should now allow constructs like this:

```
THGROUP_TYPE MyThrusterGroup = (THGROUP_TYPE)(THGROUP_USER+1);
```

which then allows to use MyThrusterGroup anywhere a THGROUP_TYPE is expected. Does this work for you?

**Comment by spacex15** [comment]
Yes @mschweiger , I tried GetThrusterGroupLevel((THGROUP_TYPE)(THGROUP_USER + indexgroup))
and it works now

thanks

**Pull request merged**
