### PR TITLE
Lua additions/fixes

### PR DESCRIPTION
**Pull request by schnepe2**
- fixed vessel:set_touchdownpoints()
- minor ldoc documentation comment fixes.
- added unit tests.

Pull request procedure test ;)

### CODE REVIEW

**Comment by schnepe2** [comment]
Damn it, git distracts me so much from "the real" work ;)
Must have forgotten a header or so.

**Comment by schnepe2** [comment]
I have to get the build process working on my machine first!
So closing this PR.
Sorry for the distraction ;)

**Comment by mschweiger** [comment]
No problem. Appreciate your effort on the code. I couldn't actually figure out why the build failed, so was trying to check out the pull request without merging (gh pr checkout 67) but got into a battle with github command line authentication ...

**Comment by mschweiger** [comment]
Hi Kuddel, I have a fix. But you need to give me permission to push it to your pull request.
[https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork](url)

**Comment by schnepe2** [comment]
Thank you for taking a look.
I have closed this PR for now as I wanted to make sure I can build it locally - to make it as easy for you to merge it.
I've "allowed edits by maintainers", but I'm not sure if this works with closed PRs.

I am used to github repositories where only PRs are accepted with "no issues at all"...so I'm not used to this politeness 👍

**Comment by schnepe2** [comment]
This seems to get build now 👍 

One thing I've noticed: There are two (identical) headers for Interpreter:
- `Src\Module\LuaScript\LuaInterpreter\Interpreter.h`
- `Orbitersdk\include\Interpreter.h`

I guess this resulted from the "closed-source" days of Orbiter.
Can one these be removed? I think the file in the `include` directory is obsolete now, right?

**Comment by mschweiger** [comment]
Yes, exactly, the Interpreter.h in Orbitersdk/include was the problem. I have removed this from the source tree now and am referencing the one in Src/Module/LuaScript/LuaInterpreter instead. Interpreter.h is still deployed to Orbitersdk/include in the build directory.

The PR builds now ok. If you are happy with it I'll merge it.

**Comment by schnepe2** [comment]
> The PR builds now ok. If you are happy with it I'll merge it.
It would be an honor 😁

**Comment by mschweiger** [comment]
All done. Thanks!

**Pull request merged**
