### PR TITLE
Disable min/max macros from windows.h

### PR DESCRIPTION
**Pull request by TheGondos**
This PR is about removing the min/max macros that are defined by default in windows.h.
Using the /DNOMINMAX flag, they are not defined and we can use the functions from the C++ library.
Impacts :
- both operands of std::min/std::max must be of the same type so there is a bunch of casting/constants rework
- since there are already some "using namespace std" present in the base code, I didn't want to have half the code using std::min/std::max and the other just min/max. As a result I added a bunch of "using std::min/max" to keep consistency.
- std::min/std::max form is still used in the header files to prevent polluting the global namespace

### CODE REVIEW

**Comment by TheGondos** [comment]
Work around for [another issue](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBJcpAAOqAqETgwe3r56icmOAkEh4SxRMVxxdpgOqUIETMQE6T5%2BZZj2uQzVtQT5YZHRsbY1dQ2ZZYNdwT1FfaUAlLaoXsTI7BzmAMzByN5YANQma25iwCSECCz72CYaAIJX11S0qEwEOyxMqmvUj887TKQ7DyeLwi/0BP2QMzuJgA7FYbjsETtiJgCIsGDsFAR0CAQG9VBA/hisTi8RAQRDIWs4bdoQARO5gl54tYRL5A36g77AznsiFQ2F3RFIlFoonY3HvCAwiyE8kw2mU6nyu4cOa0TgAVl4fg4WlIqE4bms1gxCyWmD2ZjWPFIBE0qrmAGsQGs1gA6V2er3egBs%2Bk4km19v1nF4ChAGlt9rmcFgSDQLHidGi5EoCaT9BiADdkPF4gB9LNcACc%2BYMBEwmPzqh90iwWbwywAanhMAB3ADy8UYnBtNFoFeI4bJwYiwVqAE9e7wx8xiBOOxFtBU7dxeAm2IIOwxaFPdbwsBEvMBDrRaOG16QsG8jOJ91e8MjKlnK8HMKoKl4K9PyIIWsHaDwCJiEnDwsB/AhiDwFhpzmB4mGABQW3bLse0vfhBBEMR2CkGRBEUFR1HvXQ4gMIwUGNSx9CA8NIDmVB4jaC8AHpMWxUxLGsLhoR2ZiOzMXhUBfYgoKwWiIDmcpKmcCBXGGJpSECCZCmKLIkhSAR5LUnJUm6FTplsFoVyqMYtOaVoTM6PTehKAZOjMuy6msqYSkks1lgkNVNSDe8DQ4HYa0kV4FBzHYi2LN1y0rF4IFwQgSEta0Zl4VctBmJ0XXdb1ss9P11Q4QNSB1PU/LDCMo33GMYEQFBUETZMyAoCB0wakBgC4a0r0wBtm1bTtux1Ps6EHYcIlHcd5x/WdJ0XZcHB/DdGAIbdd2DQ9j1Pc8f2vQxgDvPV8CfRwXwvPV30/b9L2CCt8r1QDgNAjAVhtSDoNgvgDEQ5D%2BrQvtZCw8RcIw%2BQlDUYNdDMfRdooziqPu8T6MY1ILwAWjY/ZaQ4qxLG4nYUf4wThNE186MMiyZLkzxGn8Bh0Gc1S4myDS0ipkYEnUtp6YMqS2g6IZWYUnnLKc5SbL0TF7IF8Wxi51z5kWDyuC8jgtSK4M/ICgAOH0UdrHZgGQZAdg6t0uB2WL8CIYhEqVlLowy10PRy7L/QKnyStDWxytSh1XYEtXfM9n30tIYTkmcSQgA%3D%3D%3D) with MSVC that prevent using initializer lists when min/maxing 3 values.

**Comment by dimitry-ishenko** [comment]
> For what it's worth, I tried replacing some min(max(x,a),b) with std::clamp but both gcc and MSVC generate [garbage assembly](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBJcpAAOqAqETgwe3r56icmOAkEh4SxRMVxxdpgOqUIETMQE6T5%2BZZj2uQzVtQT5YZHRsbY1dQ2ZZYNdwT1FfaUAlLaoXsTI7BzmAMzByN5YANQma25iwCSECCz72CYaAIJX11S0qEwEOwrPi8%2BYAPpbrPHUj2eOwAbjM9gB2Kw3HYwnbETAERYMV4EdAgFAGFj/YGkHYaAB0VFxXEJM32UNu4IAIncHk8Xm9EcRPl96MAmMgAJ4A%2BkgsEmSF3WEgvZrKk7CDA0VuPH4jRUflrABisvlOxAIPJQthUv24slouwOxJ8sVKpNVHVmrWFOF8KZyOBWpuAppNw4c1onAArLw/BwtKRUJw3NZrK8FktMHszGseKQCJoPXMANYgNZrfEZ7M53MANn0nEkfqTQc4vAUIA0CaTczgsCQaCxdGi5EoTfiLZiwOQ8XiX2BXAAnKzPgoCF9VHnpFhgXhlgA1PCYADuAHl4oxOPGaLQCNFKxAIqWIsFapzt7xT8xiJy1xFtBVE9xeE22II1wxaBeA7wsBEvGAQ5aFoSsX1ILAWEMYBxF/CC8HhSpgUwMDA0wVQKi8fdL3IQQWlLWg8AiZlbw8LAcIIYg8BYS85geJhgAUJdVw3LdwP4QQRDEdgpBkQRFBUdQ4N0OIDCMFAw0sfQiMrSA5lQeI2jAgB6cc0VMSxrC4cEdmUtczF4VBkOIKisFkiA5nKSpnAgVxhiaUhAgmQpiiyJIUgEey3JyVJuhc6ZbBaJ8qjGLzmlaELOj83oSgGTowriupoqmEpLMjZYJE9H0Szg4MOB2KdJB2FgFB7EFh3xAx93HCVcEIEgYzjGZeGfLQZlTdNM1zbrswLL0OGLUh/UDPKKyrGtfzrGBEBQVBm3oMgKAgDsuxAYAuDjCDMDnRdl3XTd/R3Oh92IQ9jzg69zxwy7b3vR8HBwt9GAIT9v1Lf9AOA0CcMg6DYMDfBEMcZDUN4dDMOw8Dgn3frA0I4jzzIlZ40o6jaL4AxGOY/a2J3WQuPEXiOPkJQ1FLXQzH0aCJM0qT4fM%2BTFNSMCAFo1L1DSrEsbSdhZ/TDOM0yUPgSygusvxbIYdxPEafwpeS1y4myDy0hlkYEnctoFYCqy2g6IY1Yc3XIqS5yYr0cd4sNi2xm11L5kWDKuCyjhfSG0s8oKgAOPMWenHZgGQZBjUzLhavwIhiEa52WtrDqMyzHrusLAacpG8tbHG1rkxTgz3dyjPs/a0hjOSZxJCAA%3D%3D%3D) so I did not pursue the matter. Come on C++, where is the zero cost abstraction you always brag about :(

@TheGondos why do you say garbage? It looks totally fine and is half the size of the home-grown solution

**Comment by TheGondos** [comment]
> > For what it's worth, I tried replacing some min(max(x,a),b) with std::clamp but both gcc and MSVC generate [garbage assembly](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBJcpAAOqAqETgwe3r56icmOAkEh4SxRMVxxdpgOqUIETMQE6T5%2BZZj2uQzVtQT5YZHRsbY1dQ2ZZYNdwT1FfaUAlLaoXsTI7BzmAMzByN5YANQma25iwCSECCz72CYaAIJX11S0qEwEOwrPi8%2BYAPpbrPHUj2eOwAbjM9gB2Kw3HYwnbETAERYMV4EdAgFAGFj/YGkHYaAB0VFxXEJM32UNu4IAIncHk8Xm9EcRPl96MAmMgAJ4A%2BkgsEmSF3WEgvZrKk7CDA0VuPH4jRUflrABisvlOxAIPJQthUv24slouwOxJ8sVKpNVHVmrWFOF8KZyOBWpuAppNw4c1onAArLw/BwtKRUJw3NZrK8FktMHszGseKQCJoPXMANYgNZrfEZ7M53MANn0nEkfqTQc4vAUIA0CaTczgsCQaCxdGi5EoTfiLZiwOQ8XiX2BXAAnKzPgoCF9VHnpFhgXhlgA1PCYADuAHl4oxOPGaLQCNFKxAIqWIsFapzt7xT8xiJy1xFtBVE9xeE22II1wxaBeA7wsBEvGAQ5aFoSsX1ILAWEMYBxF/CC8HhSpgUwMDA0wVQKi8fdL3IQQWlLWg8AiZlbw8LAcIIYg8BYS85geJhgAUJdVw3LdwP4QQRDEdgpBkQRFBUdQ4N0OIDCMFAw0sfQiMrSA5lQeI2jAgB6cc0VMSxrC4cEdmUtczF4VBkOIKisFkiA5nKSpnAgVxhiaUhAgmQpiiyJIUgEey3JyVJuhc6ZbBaJ8qjGLzmlaELOj83oSgGTowriupoqmEpLMjZYJE9H0Szg4MOB2KdJB2FgFB7EFh3xAx93HCVcEIEgYzjGZeGfLQZlTdNM1zbrswLL0OGLUh/UDPKKyrGtfzrGBEBQVBm3oMgKAgDsuxAYAuDjCDMDnRdl3XTd/R3Oh92IQ9jzg69zxwy7b3vR8HBwt9GAIT9v1Lf9AOA0CcMg6DYMDfBEMcZDUN4dDMOw8Dgn3frA0I4jzzIlZ40o6jaL4AxGOY/a2J3WQuPEXiOPkJQ1FLXQzH0aCJM0qT4fM%2BTFNSMCAFo1L1DSrEsbSdhZ/TDOM0yUPgSygusvxbIYdxPEafwpeS1y4myDy0hlkYEnctoFYCqy2g6IY1Yc3XIqS5yYr0cd4sNi2xm11L5kWDKuCyjhfSG0s8oKgAOPMWenHZgGQZBjUzLhavwIhiEa52WtrDqMyzHrusLAacpG8tbHG1rkxTgz3dyjPs/a0hjOSZxJCAA%3D%3D%3D) so I did not pursue the matter. Come on C++, where is the zero cost abstraction you always brag about :(
> 
> @TheGondos why do you say garbage? It looks totally fine and is half the size of the home-grown solution

Home grown solution : 3ops, one memory access
```
float saturate_legacy(float) PROC                     ; saturate_legacy, COMDAT
        xorps   xmm1, xmm1
        maxss   xmm1, xmm0
        movss   xmm0, DWORD PTR __real@3f800000
        minss   xmm0, xmm1
        ret     0
float saturate_legacy(float) ENDP                     ; saturate_legacy
```
std::clamp : 7ops, 5 memory accesses
```
float saturate_clamp(float) PROC                            ; saturate_clamp, COMDAT
        lea     rax, QWORD PTR v$[rsp]
        movss   DWORD PTR [rsp+8], xmm0
        xorps   xmm1, xmm1
        mov     DWORD PTR $T2[rsp], 1065353216            ; 3f800000H
        comiss  xmm1, xmm0
        lea     rcx, QWORD PTR $T1[rsp]
        mov     DWORD PTR $T1[rsp], 0
        cmovbe  rcx, rax
        lea     rax, QWORD PTR $T2[rsp]
        comiss  xmm0, DWORD PTR __real@3f800000
        cmovbe  rax, rcx
        movss   xmm0, DWORD PTR [rax]
        ret     0
float saturate_clamp(float) ENDP
```
I wouldn't call that totally fine

**Comment by dimitry-ishenko** [comment]
@TheGondos oh sorry, for some reason they are reversed in the assembly window. I didn't look at the labels and thought the top part was for the clamp version. Nevermind.

**Comment by dimitry-ishenko** [comment]
Clang on the other hand does well on both: https://godbolt.org/z/Pre1r81jf

**Comment by Xyon** [comment]
@TheGondos think you missed an `#include <algorithm>` in DrawAPI.h?

**Comment by TheGondos** [comment]
> @TheGondos think you missed an `#include <algorithm>` in DrawAPI.h?

Let me check, it builds cleanly on my side. I'll rebase to see if it's a conflict

**Comment by TheGondos** [comment]
I manually put the files for irrKlang, it should be OK. I forced pushed a rebase from the latest main.

**Comment by dimitry-ishenko** [comment]
@TheGondos unfortunately this PR had unintended consequences for addon developers. Since you've made changes to the `DrawAPI.h` and `VesselAPI.h` in the SDK, the addon devs also have to add `NOMINMAX` in their projects to disable Windows macros or they get errors.

There is a pretty simple fix though -- just wrap all `std::min` and `std::max` instances in parens. Eg:
```diff
-    foo = std::max(bar, baz);
+    foo = (std::max)(bar, baz);
```

**Comment by dimitry-ishenko** [comment]
Nevermind, I've just sent a PR #365 myself

**Pull request merged**
