### PR TITLE
Fix for #410 (unpredictable precision) 

### PR DESCRIPTION
**Pull request by schnepe2**
Fixes issue #410
Floating point output stream formatter added to serialize double/float values nice & tidy.

### CODE REVIEW

**Comment by jarmonik** [comment]
Does this reduce the precision of things like vessel state vectors or (lng, lat) information in scenario files ?

**Comment by schnepe2** [comment]
No, it doesn't.
Vessel state vectors might get a little better precision if anything would change.
It depended a lot on which MFD was set and/or what camara mode - hence unpredictable.
But never was it left any better than 6.

**Comment by schnepe2** [comment]
I've looked at some "prominent" Vessel Addons to see whether they use oapiWriteScenario_float or `oapiWriteScenario_vec` but it seems almost all used the "`oapiWriteScenario_string` work-around" - as that was the only way to guarantee the output format accuracy/precision until now.
So: confidence is high! 😄

**Comment by jarmonik** [comment]
Ok, Thanks.  Ready for merge ?

**Comment by schnepe2** [comment]
Yes, ready.

**Pull request merged**
